import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {z} from 'zod';
import {mirrorSheets,readSheetsProgram} from '@/lib/sheets';
const row=z.object({uuid:z.string().uuid(),seance_uuid:z.string().uuid(),date:z.string(),heure_debut:z.string(),seance_id:z.string(),exercice_id:z.string(),index_serie:z.number().int().min(1).max(100),cote:z.enum(['gauche','droite','bilateral']),charge_kg:z.number().min(0).max(2000),charge_libelle:z.string().max(100),reps_prevues:z.number().min(0).max(1000),reps_faites:z.number().min(0).max(1000),duree_s:z.number().min(0).max(86400),rir_ressenti:z.number().min(0).max(10).nullable(),approche:z.boolean(),valide_auto:z.boolean(),intercalaire:z.boolean().optional()});
const session=z.object({seance_uuid:z.string().uuid(),date:z.string(),seance_id:z.string().max(100),seance_version:z.number().int().positive(),nom:z.string().max(200),heure_debut:z.string(),heure_fin:z.string(),duree_min:z.number().min(0),exercices_prevus:z.number(),exercices_faits:z.number(),volume_kg:z.number(),rpe_global:z.number().min(1).max(10).nullable(),ressenti:z.string().max(1000),records:z.array(z.string()),statut:z.enum(['terminee','abandonnee']),series:z.array(row).max(1000),retours:z.array(z.object({uuid:z.string().uuid(),seance_uuid:z.string().uuid(),date:z.string(),exercice_id:z.string(),retour:z.enum(['ok','facile','trop_dur']),saisi_en:z.string()}))});
const payload=z.object({sessions:z.array(session).max(200),runs:z.array(z.object({uuid:z.string().uuid(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),km:z.number().min(0).max(500)})).max(500),program:z.object({catalogue:z.array(z.any()).max(500),modeles:z.array(z.any()).max(500)}).nullable()});
export async function POST(request:Request){
 if(!await getChatGPTUser())return Response.json({error:'Authentification requise'},{status:401});
 if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origine refusée'},{status:403});
 try{const raw=await request.text();if(raw.length>2000000)return Response.json({error:'Données trop volumineuses'},{status:413});const parsed=payload.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Données invalides'},{status:400});const data=parsed.data,db=env.DB;if(!db)throw Error('Database unavailable');const now=Date.now();const statements=[...data.sessions.map(s=>db.prepare('INSERT INTO sessions (id,payload,updated) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind(s.seance_uuid,JSON.stringify(s),now)),...data.runs.map(r=>db.prepare('INSERT INTO runs (id,payload,updated) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind(r.uuid,JSON.stringify(r),now))];if(data.program)statements.push(db.prepare('INSERT INTO program (id,payload,updated) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind('current',JSON.stringify(data.program),now));for(let i=0;i<statements.length;i+=50)await db.batch(statements.slice(i,i+50));
 const [ss,rr,pp]=await Promise.all([db.prepare('SELECT payload FROM sessions ORDER BY updated DESC').all<{payload:string}>(),db.prepare('SELECT payload FROM runs ORDER BY updated DESC').all<{payload:string}>(),db.prepare('SELECT payload FROM program WHERE id=?').bind('current').first<{payload:string}>()]);let sessions=ss.results.map(x=>JSON.parse(x.payload)),program=pp?JSON.parse(pp.payload):null;let sheets=false,sheetsError:string|undefined;
 try{const result=await mirrorSheets(data.sessions,data.program);sheets=result.enabled;if(sheets){const source=await readSheetsProgram();if(source.program)program=source.program;if(source.sessions?.length)sessions=source.sessions;}}catch(e){console.error('Sheets sync failed',e instanceof Error?e.message:'error');sheetsError='Google Sheets indisponible ; sauvegarde privée conservée.'}
 return Response.json({sessions,runs:rr.results.map(x=>JSON.parse(x.payload)),program,sheets,sheetsError},{headers:{'Cache-Control':'no-store'}});
 }catch(e){console.error('Sync failed',e instanceof Error?e.message:'error');return Response.json({error:'Synchronisation indisponible'},{status:503})}
}
