import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {compile,enter,makeRun,suggest,taskLoad,finishRun,startExecution,rowFor} from '../lib/engine.ts';import type {Program,Session,Row} from '../lib/types.ts';
const p=JSON.parse(readFileSync(new URL('../public/data/programme.json',import.meta.url),'utf8')) as Program;const model=p.modeles.find(m=>m.id==='bas_lourde')!;const squat=p.catalogue.find(e=>e.id==='squat')!,entry=model.exercices.find(e=>e.exercice_id==='squat')!;
const session=(days:number,feedback='ok',reps=5,charge=50):Session=>({seance_uuid:crypto.randomUUID(),date:'2026-10-01',seance_id:'bas_lourde',seance_version:1,nom:'Test',heure_debut:new Date(Date.now()-days*86400000).toISOString(),heure_fin:new Date().toISOString(),duree_min:45,exercices_prevus:3,exercices_faits:3,volume_kg:1000,rpe_global:5,ressenti:'',records:[],statut:'terminee',series:Array.from({length:4},(_,i)=>({exercice_id:'squat',charge_kg:charge,reps_faites:reps,approche:false,cote:'bilateral',index_serie:i+1} as Row)),retours:[{exercice_id:'squat',retour:feedback} as any]});
test('demo catalogue and models are consistent',()=>{assert.equal(p.catalogue.length,34);assert.equal(p.modeles.length,5);for(const m of p.modeles)for(const e of m.exercices)assert.ok(p.catalogue.some(x=>x.id===e.exercice_id))});
test('no history asks for initial load',()=>assert.equal(suggest(squat,entry,model.id,[]).charge,null));
test('two full sessions progress, a hard feedback cancels progression',()=>{assert.equal(suggest(squat,entry,model.id,[session(2),session(9)]).charge,55);assert.equal(suggest(squat,entry,model.id,[session(2,'trop_dur'),session(9)]).charge,45);assert.equal(suggest(squat,entry,model.id,[session(2,'facile'),session(9)]).charge,60)});
test('failed sets do not automatically reduce load',()=>assert.equal(suggest(squat,entry,model.id,[session(2,'ok',3)]).charge,50));
test('long breaks reduce load or request fresh discovery',()=>{assert.equal(suggest(squat,entry,model.id,[session(30)]).charge,40);assert.equal(suggest(squat,entry,model.id,[session(70)]).charge,null)});
test('90% references heavy session once',()=>assert.equal(suggest(squat,entry,'bas_90',[session(2)]).charge,45));
test('warm-ups precede work, and inserts preserve all sets and sides',()=>{for(const m of p.modeles){const tasks=compile(m,p,false,5),all=tasks.flatMap(t=>t.kind==='set'?[t]:t.fillers??[]);for(const e of m.exercices.filter(e=>!e.jours||e.jours.includes(5))){const ex=p.catalogue.find(x=>x.id===e.exercice_id)!;assert.equal(all.filter(t=>t.ex.id===e.exercice_id&&!t.approach).length,e.series*(ex.unilateral?2:1),m.id+':'+ex.id)}if(m.id.startsWith('bas'))assert.deepEqual(tasks.filter(t=>t.ex.id==='squat'&&t.kind==='set').slice(0,3).map(t=>t.factor),[0,.5,.8])}});
test('reduced sessions retain warm-up and halve force volume',()=>{const tasks=compile(model,p,true);assert.equal(tasks.filter(t=>t.ex.id==='squat'&&t.kind==='set'&&!t.approach).length,2);assert.equal(tasks.filter(t=>t.ex.id==='squat'&&t.kind==='set'&&t.approach).length,3)});
test('absolute deadlines remain correct on resumed execution',()=>{const run=makeRun(model,p,[],false);const count=enter(run,0,1000);assert.equal(count.deadline,6000);assert.equal(count.deadline!-4000,2000)});
test('saved workout retains exact programme version',()=>{const run=makeRun({...model,version:4},p,[],false);assert.equal(finishRun(run,[]).seance_version,4)});
test('starting now gives timed exercises their full duration and cannot restart an active set',()=>{
 const run=makeRun(model,p,[],false);
 const cursor=run.tasks.findIndex(t=>t.kind==='set'&&t.seconds>0);
 assert.ok(cursor>=0);
 const countdown=enter(run,cursor,1000);
 const started=startExecution(countdown,2000);
 assert.equal(started.phase,'EXECUTION');
 assert.equal(started.executionAt,2000);
 assert.equal(started.deadline,2000+run.tasks[cursor].seconds*1000);
 assert.equal(startExecution(started,2500),started);
 const paused={...countdown,pausedAt:1500};
 assert.equal(startExecution(paused,2000),paused);
 const repsCursor=run.tasks.findIndex(t=>t.kind==='set'&&t.seconds===0);
 const reps=startExecution({...enter(run,repsCursor,1000),phase:'COUNTDOWN'},2000);
 assert.equal(reps.phase,'EXECUTION');
 assert.equal(reps.deadline,null);
 assert.equal(rowFor(reps,run.tasks[repsCursor],20,false,false,12000).duree_s,10);
});
test('exercise review waits eight seconds even in an existing workout snapshot',()=>{
 const run=makeRun(model,p,[],false);
 const cursor=run.tasks.findIndex(t=>t.kind==='review');
 run.tasks[cursor]={...run.tasks[cursor],seconds:5};
 const review=enter(run,cursor,1000);
 assert.equal(review.phase,'REVIEW');
 assert.equal(review.deadline,9000);
});
test('skipping recovery drops unfinished inserts and preserves completed rows',()=>{
 const run=makeRun(model,p,[],false);
 const cursor=run.tasks.findIndex(t=>t.kind==='rest'&&(t.fillers?.length??0)>1);
 assert.ok(cursor>=0);
 const rest=enter(run,cursor,1000);
 const completed=rowFor(rest,rest.tasks[cursor].fillers![0],20,false,true,2000);
 const next=enter({...rest,rows:[completed],fillerIndex:1},cursor+1,3000);
 assert.equal(next.cursor,cursor+1);
 assert.deepEqual(next.rows,[completed]);
 assert.equal(next.fillerIndex,0);
 assert.deepEqual(next.fillerDone,[]);
});
