import {env} from 'cloudflare:workers';
import type {Session,Program} from './types';
// The service-account private key is read only in the Worker. It is never bundled for the browser.
const config=()=>env as unknown as {GOOGLE_SERVICE_ACCOUNT_JSON?:string;GOOGLE_SHEET_ID?:string};
let tokenCache:{token:string;until:number}|null=null;
function b64(s:string|Uint8Array){const bytes=typeof s==='string'?new TextEncoder().encode(s):s;let v='';for(const b of bytes)v+=String.fromCharCode(b);return btoa(v).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function token(){if(tokenCache&&tokenCache.until>Date.now())return tokenCache.token;const key=JSON.parse(config().GOOGLE_SERVICE_ACCOUNT_JSON!);const now=Math.floor(Date.now()/1000);const unsigned=b64(JSON.stringify({alg:'RS256',typ:'JWT'}))+'.'+b64(JSON.stringify({iss:key.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const pem=key.private_key.replace(/-----[^-]+-----/g,'').replace(/\s/g,'');const imported=await crypto.subtle.importKey('pkcs8',Uint8Array.from(atob(pem),c=>c.charCodeAt(0)),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',imported,new TextEncoder().encode(unsigned));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:unsigned+'.'+b64(new Uint8Array(signature))})});if(!r.ok)throw Error('Google credentials refused');const d=await r.json() as {access_token:string};tokenCache={token:d.access_token,until:Date.now()+3300000};return d.access_token}
async function google(path:string,init:RequestInit={}){const r=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+config().GOOGLE_SHEET_ID+path,{...init,headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json',...init.headers}});if(!r.ok)throw Error('Google Sheets '+r.status);return r.json() as Promise<any>}
const enabled=()=>Boolean(config().GOOGLE_SERVICE_ACCOUNT_JSON&&config().GOOGLE_SHEET_ID);
const objects=(values:any[][])=>{const [headers,...rows]=values??[];return rows.map(r=>Object.fromEntries(headers.map((h:any,i:number)=>[h,r[i]??''])))};
const sheetColumns={series:['uuid','seance_uuid','date','heure_debut','seance_id','exercice_id','index_serie','cote','charge_kg','charge_libelle','reps_prevues','reps_faites','duree_s','rir_ressenti','approche','valide_auto','intercalaire','mesure','distance_m','charge_applicable','echauffement'],seances:['seance_uuid','date','seance_id','seance_version','nom','heure_debut','heure_fin','duree_min','exercices_prevus','exercices_faits','volume_kg','rpe_global','ressenti','records','statut'],retours_exercice:['uuid','seance_uuid','date','exercice_id','retour','saisi_en']};
export async function mirrorSheets(sessions:Session[],program:Program|null){if(!enabled())return {enabled:false};
 // Upsert only submitted sessions: do not overwrite manual edits to older spreadsheet rows.
 for(const [name,columns] of Object.entries(sheetColumns)){const incoming=sessions.flatMap<any>(s=>name==='series'?s.series:name==='retours_exercice'?s.retours:[s]) as unknown as Record<string,unknown>[];if(!incoming.length)continue;const existing=await google('/values/'+encodeURIComponent(name+'!A1:AZ50000'));const values=existing.values??[],indexes=new Map(values.slice(1).map((r:any[],i:number)=>[String(r[0]),i+2]));const updates:any[]=[{range:name+'!A1',values:[columns]}];const append:any[]=[];for(const row of incoming){const cells=columns.map(k=>Array.isArray(row[k])?JSON.stringify(row[k]):row[k]??'');const index=indexes.get(String(row[columns[0]]));if(index)updates.push({range:name+'!A'+index,values:[cells]});else append.push(cells)}if(updates.length)await google('/values:batchUpdate',{method:'POST',body:JSON.stringify({valueInputOption:'RAW',data:updates})});if(append.length)await google('/values/'+encodeURIComponent(name+'!A:AZ')+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS',{method:'POST',body:JSON.stringify({values:append})});}
 if(program){const columns=['seance_id','seance_nom','ordre','exercice_id','series','reps_min','reps_max','repos_s','intercalaire_de','approche','note','version','actif_du','actif_au','duree_s','jours','duree_min','archive','format','mesure','distance_m','steps','cycle','revision','program_revision'];const values=program.modeles.flatMap(m=>m.exercices.map(e=>[m.id,m.nom,e.ordre,e.exercice_id,e.series,e.reps_min,e.reps_max,e.repos_s,JSON.stringify(e.intercalaire_de),e.approche,e.note,m.version,m.actif_du,m.actif_au,e.duree_s,JSON.stringify(m.jours),m.duree_min,m.archive,e.format,e.mesure??'',e.distance_m??'',JSON.stringify(e.steps??null),JSON.stringify(e.cycle??null),e.revision??0,program.revision??0]));await google('/values/'+encodeURIComponent('seances_modeles!A1')+'?valueInputOption=RAW',{method:'PUT',body:JSON.stringify({values:[columns,...values]})});}
 return {enabled:true}}
export async function readSheetsProgram(){if(!enabled())return {};const data=await google('/values:batchGet?ranges=catalogue_exercices!A1:AZ1000&ranges=seances_modeles!A1:AZ5000&ranges=series!A1:AZ50000&ranges=seances!A1:AZ5000&ranges=retours_exercice!A1:AZ50000');const [cat,models,rows,sessions,feedback]=data.valueRanges.map((r:any)=>objects(r.values));const bool=(v:any)=>v===true||String(v).toLowerCase()==='true'||v===1;const json=(v:any,def:any)=>{try{return JSON.parse(String(v))}catch{return def}};
 let modelMap=new Map<string,any>();for(const r of models){const key=r.seance_id+':'+r.version;let m=modelMap.get(key);if(!m){m={id:r.seance_id,nom:r.seance_nom,sous_titre:'',version:Number(r.version)||1,actif_du:r.actif_du,actif_au:r.actif_au,jours:json(r.jours,[]),duree_min:Number(r.duree_min)||45,archive:bool(r.archive),exercices:[]};modelMap.set(key,m)}m.exercices.push({exercice_id:r.exercice_id,ordre:Number(r.ordre),series:Number(r.series),reps_min:Number(r.reps_min),reps_max:Number(r.reps_max),duree_s:Number(r.duree_s),repos_s:Number(r.repos_s),intercalaire_de:json(r.intercalaire_de,[]),approche:bool(r.approche),format:r.format,note:r.note,mesure:['reps','duration','distance','execution'].includes(r.mesure)?r.mesure:undefined,distance_m:r.distance_m===''||r.distance_m===undefined?undefined:Number(r.distance_m),steps:json(r.steps,undefined)??undefined,cycle:json(r.cycle,undefined)??undefined,revision:Number(r.revision)||0})}
 const programme=cat.length&&modelMap.size?{revision:Math.max(0,...models.map((r:any)=>Number(r.program_revision)||0)),catalogue:cat.map((r:any)=>({...r,unilateral:bool(r.unilateral),increment_kg:Number(r.increment_kg)||2.5})),modeles:[...modelMap.values()]} as Program:null;
 const numeric=['index_serie','charge_kg','reps_prevues','reps_faites','duree_s'];const sr=rows.map((r:any)=>({...r,...Object.fromEntries(numeric.map(k=>[k,Number(r[k])||0])),approche:bool(r.approche),valide_auto:bool(r.valide_auto),intercalaire:bool(r.intercalaire),echauffement:r.echauffement===''||r.echauffement===undefined?undefined:bool(r.echauffement),mesure:['reps','duration','distance','execution'].includes(r.mesure)?r.mesure:undefined,distance_m:r.distance_m===''||r.distance_m===undefined?undefined:Number(r.distance_m),charge_applicable:r.charge_applicable===''||r.charge_applicable===undefined?undefined:bool(r.charge_applicable),rir_ressenti:r.rir_ressenti===''?null:Number(r.rir_ressenti)}));return {program:programme,sessions:sessions.map((s:any)=>({...s,seance_version:Number(s.seance_version)||1,duree_min:Number(s.duree_min),volume_kg:Number(s.volume_kg),exercices_prevus:Number(s.exercices_prevus),exercices_faits:Number(s.exercices_faits),rpe_global:s.rpe_global===''?null:Number(s.rpe_global),records:json(s.records,[]),series:sr.filter((r:any)=>r.seance_uuid===s.seance_uuid),retours:feedback.filter((r:any)=>r.seance_uuid===s.seance_uuid)})) as Session[]}}
