import {migrateData,migrateProgram} from './migrations.ts';
import {rowMeasure,rowDistance} from './activity.ts';
import type {LocalData,Program,Run,Session,RunLog,Settings} from './types';
const KEY='state';let dbPromise:Promise<IDBDatabase>|null=null;
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('elan-training',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
export interface DataStore{load():Promise<LocalData>;persist(data:LocalData):Promise<void>;sync(data:LocalData):Promise<{data:LocalData;sheets:boolean;sheetsError?:string}>}
export class TrainingStore implements DataStore{
 private defaults:Program|null=null;
 private writes=Promise.resolve();
 async load(){const d=await db();const saved=await new Promise<LocalData|undefined>((res,rej)=>{const r=d.transaction('data').objectStore('data').get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});let program:Program;try{const r=await fetch('/data/programme.json');if(!r.ok)throw Error('Le programme ne peut pas être chargé.');program=await r.json() as Program}catch(error){if(saved)return saved;throw error}this.defaults=program;if(saved){const updated=migrateData(saved,program);await this.persist(updated);return updated;}const initial:LocalData={program,sessions:[],running:null,runs:[],settings:{audio:'beeps',barKg:20,reduced:false,sheetsUrl:''},pending:[],lastSync:null};await this.persist(initial);return initial}
 persist(data:LocalData){const snapshot=structuredClone(data);this.writes=this.writes.catch(()=>{}).then(async()=>{const d=await db();await new Promise<void>((res,rej)=>{const tx=d.transaction('data','readwrite');tx.objectStore('data').put(snapshot,KEY);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error??new Error('Sauvegarde interrompue'))})});return this.writes}
 async sync(local:LocalData){const ids=[...local.pending];const sessions=local.sessions.filter(s=>ids.includes(s.seance_uuid));const runs=local.runs.filter(r=>ids.includes(r.uuid));const response=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessions,runs,program:ids.includes('program')?local.program:null}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(response.status===401?'Reconnecte-toi pour synchroniser.':'La sauvegarde en ligne réessaiera automatiquement.');const remote=await response.json() as {sessions:Session[];runs:RunLog[];program:Program|null;sheets:boolean;sheetsError?:string};const merged={...local,sessions:remote.sessions as Session[],runs:remote.runs as RunLog[],program:this.defaults?migrateProgram(remote.program??local.program,this.defaults):remote.program??local.program,pending:local.pending.filter(id=>!ids.includes(id)),lastSync:Date.now()};return {data:merged,sheets:remote.sheets,sheetsError:remote.sheetsError};}
}
export function download(name:string,content:string,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export function exportCSV(sessions:Session[]){const rows=sessions.flatMap(s=>s.series);const columns=['uuid','seance_uuid','date','heure_debut','seance_id','exercice_id','index_serie','cote','charge_kg','charge_libelle','reps_prevues','reps_faites','duree_s','rir_ressenti','approche','valide_auto','mesure','distance_m','charge_applicable','intercalaire','echauffement'];const quote=(x:unknown)=>'"'+String(x??'').replaceAll('"','""')+'"';download('elan-series.csv','\uFEFF'+[columns.join(';'),...rows.map(r=>columns.map(k=>quote(k==='mesure'?rowMeasure(r):k==='distance_m'?(rowMeasure(r)==='distance'?rowDistance(r):''):['reps_prevues','reps_faites'].includes(k)&&rowMeasure(r)!=='reps'?'':k==='charge_kg'&&(r.charge_applicable===false||r.charge_applicable===undefined&&r.charge_kg===0)?'':r[k as keyof typeof r])).join(';'))].join('\n'),'text/csv;charset=utf-8')}
